<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.5.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateCustomerTopUpsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('customer_top_ups', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('customer_id')->nullable()->comment('顧客主表id');
            $table->integer('company_top_up_id')->nullable()->comment('購買儲值金');
            $table->integer('shop_id')->nullable()->comment('所屬商家');
            $table->integer('last_price')->nullable()->comment('餘額');
            $table->integer('discount')->nullable()->comment('折扣');
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();

            $table->index('customer_id', 'customer_id');
            $table->index('shop_id', 'shop_id');

            

        });

        

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('customer_top_ups');
    }
}
