<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.5.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateShopBusinessHoursTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('shop_business_hours', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('shop_id')->comment('所屬店家');
            $table->integer('shop_staff_id')->nullable()->comment('所屬商家員工');
            $table->tinyInteger('type')->comment('true營業/特殊false公休/同預設');
            $table->integer('week')->comment('星期幾');
            $table->time('start')->nullable()->comment('開始時間');
            $table->time('end')->nullable()->comment('結束時間');
            $table->dateTime('created_at')->nullable()->default(\DB::raw('CURRENT_TIMESTAMP'));
            $table->dateTime('updated_at')->nullable()->default(\DB::raw('CURRENT_TIMESTAMP'));

            $table->index('shop_id', 'shop_id');

            

        });

        

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('shop_business_hours');
    }
}
