<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.5.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateCustomersTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('customers', function (Blueprint $table) {
            $table->increments('id');
            $table->string('realname', 50)->nullable()->comment('名稱');
            $table->string('nickname', 50)->nullable()->comment('暱稱');
            $table->string('phone', 20)->nullable()->comment('電話');
            $table->text('minor_phones')->nullable()->comment('電話');
            $table->string('email', 255)->nullable()->comment('信箱');
            $table->string('birthday', 10)->nullable()->comment('生日');
            $table->char('sex', 1)->nullable()->comment('性別M男生F女生C中性');
            $table->text('facebook_id')->nullable();
            $table->text('facebook_name')->nullable();
            $table->text('google_id')->nullable();
            $table->text('google_name')->nullable();
            $table->text('line_id')->nullable();
            $table->text('line_name')->nullable();
            $table->string('photo', 255)->nullable()->comment('大頭照');
            $table->string('banner', 255)->nullable()->comment('背景圖');
            $table->text('note')->nullable()->comment('備註');
            $table->dateTime('login_date')->nullable();
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();
            $table->string('old_id', 20)->nullable();

            $table->index('email', 'email');
            $table->index('phone', 'phone');

            

        });

        

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('customers');
    }
}
