<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.5.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateShopServicesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('shop_services', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('shop_id')->nullable()->comment('所屬分店');
            $table->integer('shop_service_category_id')->nullable()->comment('商家分類id');
            $table->integer('company_service_id')->nullable()->comment('company建立的服務id');
            $table->string('type', 10)->nullable()->comment('service/advance');
            $table->string('name', 50)->nullable()->comment('名稱');
            $table->text('info')->nullable()->comment('簡介');
            $table->string('photo', 100)->nullable()->comment('圖片');
            $table->integer('price')->nullable()->comment('金額');
            $table->integer('basic_price')->nullable()->comment('底價');
            $table->integer('show_type')->nullable()->comment('價目顯示方式1同上2不顯示3以上4顯示文字');
            $table->string('show_text', 50)->nullable()->comment('價目顯示自定內容');
            $table->integer('show_time')->nullable()->comment('服務時間是否顯示1顯示0隱藏');
            $table->integer('service_time')->nullable()->comment('服務所需時間');
            $table->integer('lead_time')->nullable()->comment('前置時間');
            $table->integer('buffer_time')->nullable()->comment('緩衝時間');
            $table->enum('status', ['pending', 'published'])->default('published')->comment('上下架');
            $table->integer('sequence')->nullable()->comment('排序');
            $table->integer('blacklist_limit')->nullable()->default(0)->comment('黑名單限制項目1限制0不限制');
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();
            $table->string('old_id', 20)->nullable()->comment('舊資料對照');

            $table->index('shop_id', 'company_id');
            $table->index('shop_service_category_id', 'category_id');

            

        });

        

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('shop_services');
    }
}
