<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.5.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateShopVacationsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('shop_vacations', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('shop_id')->nullable()->comment('所屬分店');
            $table->integer('shop_staff_id')->nullable()->comment('所屬商家員工');
            $table->integer('type')->nullable()->comment('1區段2某些3整日');
            $table->date('start_date')->nullable()->comment('起始日');
            $table->time('start_time')->nullable()->comment('起始時間');
            $table->date('end_date')->nullable()->comment('結束日');
            $table->time('end_time')->nullable()->comment('結束時間');
            $table->string('note', 100)->nullable()->comment('備註');
            $table->dateTime('created_at')->nullable()->default(\DB::raw('CURRENT_TIMESTAMP'));
            $table->dateTime('updated_at')->nullable()->default(\DB::raw('CURRENT_TIMESTAMP'));

            $table->index('shop_id', 'shop_id');

            

        });

        

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('shop_vacations');
    }
}
