<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.5.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateShopStaffBussinessHoursTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('shop_staff_bussiness_hours', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('shop_id')->nullable()->comment('所屬店家');
            $table->integer('shop_staff_id')->nullable()->comment('所屬店家員工');
            $table->string('type', 10)->nullable()->comment('open營業closs公休');
            $table->integer('week')->nullable()->comment('星期幾');
            $table->string('start', 10)->nullable()->comment('開始時間');
            $table->string('end', 10)->nullable()->comment('結束時間');
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();

            $table->index('shop_id', 'shop_id');
            $table->index('shop_staff_id', 'shop_staff_id');

            

        });

        

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('shop_staff_bussiness_hours');
    }
}
