<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.5.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateOperatingLogsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('operating_logs', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('user_id')->nullable()->comment('操作者');
            $table->string('companyId', 10)->nullable()->comment('公司編號');
            $table->dateTime('date')->nullable()->comment('日期');
            $table->integer('operating_status_id')->nullable()->comment('操作狀態ID');
            $table->string('content', 100)->nullable()->comment('內容');
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();

            $table->index('companyId', 'companyId');

            

        });

        

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('operating_logs');
    }
}
