<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.5.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateCompanyTopUpTypeTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('company_top_up_type', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('company_top_up_id')->nullable()->comment('所屬儲值金');
            $table->integer('type')->nullable()->comment('儲值金類型');
            $table->integer('price')->nullable()->comment('贈送金額');
            $table->integer('discount')->nullable()->comment('折數');
            $table->integer('commodity_id')->nullable()->comment('集團產品/服務id');
            $table->string('self_definition', 50)->nullable()->comment('自定名稱');
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();

            $table->index('company_top_up_id', 'company_top_up_id');

            

        });

        

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('company_top_up_type');
    }
}
