<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.5.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateAlbumsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('albums', function (Blueprint $table) {
            $table->increments('id');
            $table->string('name', 50)->nullable()->comment('名稱');
            $table->text('info')->nullable()->comment('說明');
            $table->string('cover', 50)->nullable()->comment('封面照片');
            $table->integer('sequence')->nullable()->comment('排序');
            $table->string('type', 30)->nullable()->comment('collection作品集/album相簿/representative_work代表作品/post貼文');
            $table->integer('shop_id')->nullable()->comment('所屬商家');
            $table->integer('staff_id')->nullable()->comment('商家員工');
            $table->integer('bill_id')->nullable();
            $table->integer('customer_id')->nullable();
            $table->integer('post_id')->nullable()->comment('所屬貼文');
            $table->date('date')->nullable();
            $table->dateTime('created_at')->nullable()->default(\DB::raw('CURRENT_TIMESTAMP'));
            $table->dateTime('updated_at')->nullable()->default(\DB::raw('CURRENT_TIMESTAMP'));

            

            

        });

        

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('albums');
    }
}
