<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.5.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateCustomerTagsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('customer_tags', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('customer_id')->nullable()->comment('所屬會員');
            $table->string('tag', 50)->nullable()->comment('標籤名稱');
            $table->integer('count')->nullable()->comment('達成次數');
            $table->char('blacklist', 1)->nullable()->default('N')->comment('是否列黑名單');
            $table->dateTime('created_at')->nullable();
            $table->integer('updated_at')->nullable();

            $table->index('customer_id', 'customer_id');

            

        });

        

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('customer_tags');
    }
}
