<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.5.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateCustomerPersonalitiesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('customer_personalities', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('number')->nullable()->comment('數字');
            $table->string('type', 100)->nullable()->comment('主被動');
            $table->text('type_content')->nullable()->comment('主被動說明');
            $table->string('like', 255)->nullable()->comment('喜歡');
            $table->string('hate', 255)->nullable()->comment('討厭');
            $table->string('value_type', 255)->nullable();
            $table->string('values', 255)->nullable()->comment('價值觀');
            $table->string('characteristic', 255)->nullable()->comment('特色');
            $table->text('recommend')->nullable()->comment('建議');
            $table->dateTime('created_at')->nullable()->default(\DB::raw('CURRENT_TIMESTAMP'));
            $table->dateTime('updated_at')->nullable()->default(\DB::raw('CURRENT_TIMESTAMP'));
        });

        $sql = "INSERT INTO `customer_personalities` (`id`, `number`, `type`, `type_content`, `like`, `hate`, `value_type`, `values`, `characteristic`, `recommend`, `created_at`, `updated_at`)
VALUES
    (1, 1, '主動型', '讓客戶主動表達意見，客戶喜歡主導對話的發展，自己只要被動地去回應詢問就好了', '俐落專業、直奔主題 ', '不清不楚、拖泥帶水 ', '務實', '重視好處、理性', '創造力、領導力 ', '講重點不要繞，複雜的事簡單說，不喜歡強迫、被要求，要給予選擇空間。\n提供實在的產品，理性講解並給予十足的尊重。', '2021-10-22 14:36:17', '2021-10-22 14:40:39'),
    (2, 2, '被動型', '適合由你主動開啟話題，不論是閒聊生活或是講解功效，主動地跟客戶展開溝通', '和和氣氣、有人陪伴 ', '馬上決定、變來變去 ', '理想', '重視感覺、感性', '溝通力、共情力 ', '認真傾聽，釋放情感讓客戶感受關心，需要陪伴拉近關係，親密的互動，\n持續的保持聯繫。會優柔寡斷、不喜歡馬上做決定、在關鍵時需要推一把。', '2021-10-22 14:36:21', '2021-10-22 14:41:11'),
    (3, 3, '主動型', '讓客戶主動表達意見，客戶喜歡主導對話的發展，自己只要被動地去回應詢問就好了', '嘻嘻哈哈、稱兄道弟 ', '拖拖拉拉、負面掃興 ', '遠見', '重視未來', '表達力、行動力 ', '多誇獎、讚美、嘉許，給足面子、舞台。\n記得抱持熱情及激情，做事情要有效率不慢吞吞。\n給他拍拍手、幫他削蘋果、帶他看煙火、嗨了就成交不囉唆。', '2021-10-22 14:36:25', '2021-10-22 14:41:40'),
    (4, 4, '被動型', '適合由你主動開啟話題，不論是閒聊生活或是講解功效，主動地跟客戶展開溝通', '白底黑字、附加價值 ', '口說無憑、誇大其詞 ', '務實', '重視好處、理性', '規劃力、組織力 ', '守時守信說到做到，不浮誇必須實事求是，喜歡數據與資料，講清楚說明白。\n需要安全感擔心風險，害怕被欺騙，不喜歡沒憑沒據的事情。', '2021-10-22 14:36:30', '2021-10-22 14:43:37'),
    (5, 5, '主動型', '讓客戶主動表達意見，客戶喜歡主導對話的發展，自己只要被動地去回應詢問就好了', '別出心裁、自由自在', '平起平坐、轉移話題', '理想', '重視感覺、感性', '感染力、社交力 ', '天馬行空隨心所欲，重視儀式感喜歡嘗試新事物與有趣好玩的事情。\n很怕麻煩，不喜歡約束規矩太多，需要足夠良好的感覺，特別喜歡與眾不同、獨一無二的事物。', '2021-10-22 14:36:34', '2021-10-22 14:43:29'),
    (6, 6, '被動型', '適合由你主動開啟話題，不論是閒聊生活或是講解功效，主動地跟客戶展開溝通', '精緻極致、孝順愛家 ', '瑕疵將就、醜醜髒髒 ', '遠見', '重視未來', '領悟力、洞察力 ', '重視品質與價值，高CP值，注重細節且在乎長遠的利益。\n喜歡有人品、有智慧、有內涵、有品味。\n不喜歡不完美、除了自己受益以外、最好還能照顧到家人。', '2021-10-22 14:36:43', '2021-10-22 14:43:23'),
    (7, 7, '主動型', '讓客戶主動表達意見，客戶喜歡主導對話的發展，自己只要被動地去回應詢問就好了', '細水長流、眼見為憑 ', '匆匆忙忙、摸稜兩可 ', '務實', '重視好處、理性', '分析力、邏輯力 ', '實在，愛專研，比較慢熱，一開始接觸會保持距離，不喜歡不懂裝懂的人，喜歡充分準備且有能見證的案例。\n內心深處固執，不可過度催促，需要慢慢建立關係。', '2021-10-22 14:36:47', '2021-10-22 14:43:14'),
    (8, 8, '被動型', '適合由你主動開啟話題，不論是閒聊生活或是講解功效，主動地跟客戶展開溝通', '認真積極、敬業執著 ', '沒有擔當、不被尊重 ', '理想', '重視感覺、感性', '開拓力、影響力 ', '享受被需要的感覺，喜歡幫助別人，愛面子、重感情，古道熱腸，責任至上，注重口碑，朋友的事就是自己的事。\n展現勤奮、可以提出請他幫忙或是協助，但不可以沒原則，討厭沒有原則的人。', '2021-10-22 14:36:50', '2021-10-22 14:43:02'),
    (9, 9, '主動型', '讓客戶主動表達意見，客戶喜歡主導對話的發展，自己只要被動地去回應詢問就好了', '侃侃而談、遠見趨勢 ', '被看不起、絕不可能 ', '遠見', '重視未來', '公關力、整合力 ', '愛聊天很健談，喜歡別人聆聽他們的偉大的夢想及夢幻的遠景。\n典型的遠見主義者，什麼事都想得很遠，重視未來的價值及後面隱藏的商機，不喜歡被潑冷水。', '2021-10-22 14:36:52', '2021-10-22 14:42:57');
";

         \DB::statement($sql) ;

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('customer_personalities');
    }
}
