<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.5.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateShopManagementCustomerListsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('shop_management_customer_lists', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('shop_id')->nullable()->comment('所屬商家');
            $table->integer('shop_management_id')->nullable()->comment('所屬經營條件');
            $table->integer('shop_customer_id')->nullable()->comment('商家顧客');
            $table->string('phone', 20)->nullable()->comment('手機號碼');
            $table->char('type', 1)->nullable()->comment('1手機與line 2手機 3line 4line優先');
            $table->dateTime('datetime')->nullable()->comment('預約發送時間');
            $table->text('message')->nullable()->comment('發送內容');
            $table->char('status', 1)->nullable()->default('N')->comment('Y已發送N尚未發送');
            $table->char('sms', 1)->nullable()->default('N')->comment('發送簡訊Y已發送N尚未發送F失敗');
            $table->char('line', 1)->nullable()->default('N')->comment('發送line Y已發送N尚未發送F失敗');
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();

            

            

        });

        

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('shop_management_customer_lists');
    }
}
