<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.5.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateShopManagementsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('shop_managements', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('shop_id')->nullable()->comment('所屬商家');
            $table->integer('shop_management_mode_id')->nullable()->comment('使用模組');
            $table->string('type', 10)->nullable()->comment('once單次auto自動推廣');
            $table->string('name', 255)->nullable()->comment('推廣名稱');
            $table->text('message')->nullable()->comment('發送內容');
            $table->text('link')->nullable()->comment('連結');
            $table->string('shop_coupons', 100)->nullable()->comment('優惠券(複選)');
            $table->char('send_type', 1)->nullable()->comment('1手機與line 2手機 3line 4line優先');
            $table->dateTime('send_datetime')->nullable()->comment('預約發送時間');
            $table->char('send_cycle', 1)->nullable()->comment('1每天2每週3每月');
            $table->integer('send_cycle_week')->nullable()->comment('每週幾');
            $table->integer('send_cycle_day')->nullable()->comment('每個月的幾號');
            $table->integer('send_cycle_type')->nullable()->comment('1重複發送2只發一次');
            $table->char('status', 1)->nullable()->default('N')->comment('Y已發送N未發送');
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();

            $table->index('shop_id', 'shop_id');

            

        });

        

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('shop_managements');
    }
}
