<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.5.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateUsersTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('users', function (Blueprint $table) {
            $table->increments('id');
            $table->string('name', 50)->nullable()->comment('使用者名稱');
            $table->string('phone', 20)->default('')->comment('手機號碼/帳號');
            $table->string('photo', 255)->nullable()->comment('大頭照');
            $table->string('banner', 255)->nullable()->comment('背景圖');
            $table->string('password', 255)->default('')->comment('密碼');
            $table->string('random', 6)->nullable()->comment('隨機密碼');
            $table->string('code', 11)->nullable()->comment('推薦人的user_id');
            $table->integer('direct_sales_mode')->nullable()->comment('經銷模式');
            $table->integer('direct_sales_point')->nullable()->comment('經銷獲得點數');
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();

            

            

        });

        

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('users');
    }
}
