<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.5.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateCustomerCouponsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('customer_coupons', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('customer_id')->nullable()->comment('主會員表id');
            $table->integer('company_id')->nullable()->comment('所屬集團');
            $table->integer('shop_id')->nullable()->comment('所屬商家');
            $table->integer('shop_coupon_id')->nullable()->comment('商家優惠券');
            $table->char('status', 1)->nullable()->default('N')->comment('使用狀態Y使用N未使用');
            $table->dateTime('using_time')->nullable()->comment('何時使用掉優惠券');
            $table->dateTime('created_at')->nullable()->default(\DB::raw('CURRENT_TIMESTAMP'));
            $table->dateTime('updated_at')->nullable()->default(\DB::raw('CURRENT_TIMESTAMP'));
            $table->dateTime('deleted_at')->nullable();

            $table->index('customer_id', 'customer_id');
            $table->index('shop_id', 'shop_id');
            $table->index('company_id', 'company_id');

            

        });

        

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('customer_coupons');
    }
}
