<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.5.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateDirectSalesModesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('direct_sales_modes', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('basic')->nullable();
            $table->string('basic_type', 10)->nullable()->comment('point給點數dollar給錢');
            $table->integer('plus')->nullable();
            $table->string('plus_type', 10)->nullable()->comment('point給點數dollar給錢');
            $table->integer('pro')->nullable();
            $table->string('pro_type', 10)->nullable()->comment('point給點數dollar給錢');
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();

            

            

        });

        

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('direct_sales_modes');
    }
}
