<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.5.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateShopNoticeQuestionsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('shop_notice_questions', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('shop_id')->nullable()->comment('商家id');
            $table->integer('shop_notice_id')->nullable()->comment('預約通知id');
            $table->string('name', 255)->nullable()->comment('問題');
            $table->string('type', 15)->nullable()->comment('radio單選/checkbox多選/text問答');
            $table->text('option')->nullable()->comment('選項');
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();

            

            

        });

        

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('shop_notice_questions');
    }
}
