<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.5.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateOperatingStatusTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('operating_status', function (Blueprint $table) {
            $table->increments('id');
            $table->string('name', 20)->nullable()->comment('狀態');
            $table->string('color', 20)->nullable()->comment('顏色');
            $table->string('content', 30)->nullable()->comment('內容');
            $table->char('show', 1)->nullable()->default('Y')->comment('是否顯示');

            

            

        });

        

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('operating_status');
    }
}
