<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.5.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateCompanyProgramGroupsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('company_program_groups', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('company_program_id')->nullable()->comment('所屬方案');
            $table->integer('type')->nullable()->comment('組合型態1.單選2.多選');
            $table->integer('group_id')->nullable()->comment('組別');
            $table->string('commodity_type', 10)->nullable()->comment('product/service');
            $table->integer('commodity_id')->nullable()->comment('集團產品/服務id');
            $table->integer('price')->nullable()->comment('與同仁拆帳計算金額');
            $table->integer('count')->nullable()->comment('數量');
            $table->integer('sequence')->nullable()->comment('排序');
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();

            $table->index('company_program_id', 'company_program_id');

            

        });

        

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('company_program_groups');
    }
}
