<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.5.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateCompanysTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('companys', function (Blueprint $table) {
            $table->increments('id');
            $table->string('companyId', 20)->nullable()->comment('集團代碼');
            $table->integer('buy_mode_id')->comment('購買方案id');
            $table->string('name', 50)->nullable()->comment('集團名稱');
            $table->dateTime('deadline')->nullable()->comment('使用期限');
            $table->integer('gift_sms')->nullable()->comment('贈送簡訊數量');
            $table->integer('buy_sms')->nullable()->comment('購買簡訊數量');
            $table->string('logo', 100)->nullable()->comment('集團logo照片');
            $table->string('banner', 100)->nullable()->comment('集團背景照片');
            $table->text('terms')->nullable()->comment('服務條款');
            $table->integer('notice_letter')->nullable()->default(0)->comment('1提醒簡訊數量不夠0數量充足');
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();

            $table->index('buy_mode_id', 'buy_mode_id');

            

        });

        

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('companys');
    }
}
