<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.5.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateBuyModesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('buy_modes', function (Blueprint $table) {
            $table->integer('id');
            $table->string('title', 50)->nullable()->comment('方案標題文字');
            $table->string('type', 10)->nullable();
            $table->integer('during')->nullable()->default(0)->comment('壽命(月)');
            $table->integer('company')->nullable()->comment('集團數量');
            $table->integer('shop')->nullable()->comment('店面數量');
            $table->integer('shop_price')->nullable()->comment('每加一個店面需多少錢');
            $table->integer('free_SMS')->nullable()->default(0)->comment('免費簡訊則數');
            $table->integer('free_SMS_period')->nullable()->default(0)->comment('免費簡訊週期(月)');
            $table->integer('price')->nullable()->default(0)->comment('費用');
            $table->string('menu', 255)->nullable()->comment('側邊欄');
            $table->dateTime('created_at')->nullable()->default(\DB::raw('CURRENT_TIMESTAMP'));
            $table->dateTime('updated_at')->nullable()->default(\DB::raw('CURRENT_TIMESTAMP'));
            $table->dateTime('deleted_at')->nullable();
        });

        // 匯入資料庫
        $sql = "INSERT INTO `buy_modes` (`id`, `title`, `type`, `during`, `company`, `shop`, `shop_price`, `free_SMS`, `free_SMS_period`, `price`, `menu`, `created_at`, `updated_at`, `deleted_at`)
        VALUES
            (0, '美業官網基本版', 'ba', 0, 1, 1, NULL, 0, 0, 0, 'home,store,service', '2021-06-18 10:54:07', '2021-06-18 10:54:07', NULL),
            (1, '美業官網進階版（一年份）', 'p1', 12, 1, 1, NULL, 500, 0, 9999, NULL, '2021-06-17 15:26:54', '2021-06-17 15:26:54', NULL),
            (2, '美業管家專業版（一年份）', 'a1', 12, 1, 1, NULL, 1000, 0, 18000, NULL, '2021-06-17 15:35:36', '2021-06-17 15:35:36', NULL),
            (3, '美業管家專業連鎖版（一年份）', 'g2', 12, 1, 2, 15000, 2000, 0, 33000, NULL, '2021-06-17 15:38:17', '2021-06-17 15:38:17', NULL),
            (4, '美業管家專業連鎖版（一年份）', 'g3', 12, 1, 3, 15000, 3000, 0, 48000, NULL, '2021-06-17 17:57:18', '2021-06-17 17:57:18', NULL),
            (5, '美業管家專業連鎖版（一年份）', 'g4', 12, 1, 4, 15000, 3000, 0, 63000, NULL, '2021-06-17 18:03:10', '2021-06-17 18:03:10', NULL),
            (6, '美業管家專業連鎖版（一年份）', 'g5', 12, 1, 5, 15000, 3000, 0, 78000, NULL, '2021-06-17 18:03:25', '2021-06-17 18:03:25', NULL),
            (7, '美業管家專業連鎖版（一年份）', 'g6', 12, 1, 6, 15000, 3000, 0, 93000, NULL, '2021-06-17 18:03:28', '2021-06-17 18:03:28', NULL),
            (8, '美業管家專業連鎖版（一年份）', 'g7', 12, 1, 7, 15000, 3000, 0, 108000, NULL, '2021-06-17 18:03:31', '2021-06-17 18:03:31', NULL),
            (9, '美業管家專業連鎖版（一年份）', 'g8', 12, 1, 8, 15000, 3000, 0, 123000, NULL, '2021-06-17 18:03:33', '2021-06-17 18:03:33', NULL),
            (10, '美業管家專業連鎖版（一年份）', 'g9', 12, 1, 9, 15000, 3000, 0, 138000, NULL, '2021-06-17 18:04:02', '2021-06-17 18:04:02', NULL),
            (11, '美業管家專業連鎖版（一年份）', 'g10', 12, 1, 10, 15000, 3000, 0, 153000, NULL, '2021-06-17 18:04:04', '2021-06-17 18:04:04', NULL),
            (12, '美業管家專業連鎖版（一年份）', 'g11', 12, 1, 11, 15000, 3000, 0, 168000, NULL, '2021-06-17 18:04:07', '2021-06-17 18:04:07', NULL),
            (13, '美業管家專業連鎖版（一年份）', 'g12', 12, 1, 12, 15000, 3000, 0, 183000, NULL, '2021-06-17 18:24:14', '2021-06-17 18:24:14', NULL),
            (14, '美業管家專業連鎖版（一年份）', 'g13', 12, 1, 13, 15000, 3000, 0, 198000, NULL, '2021-06-17 18:24:14', '2021-06-17 18:24:14', NULL),
            (15, '美業管家專業連鎖版（一年份）', 'g14', 12, 1, 14, 15000, 3000, 0, 213000, NULL, '2021-06-17 18:53:12', '2021-06-17 18:53:12', NULL),
            (16, '美業管家專業連鎖版（一年份）', 'g15', 12, 1, 15, 15000, 3000, 0, 228000, NULL, '2021-06-17 18:53:36', '2021-06-17 18:53:36', NULL),
            (17, '美業管家專業連鎖版（一年份）', 'g16', 12, 1, 16, 15000, 3000, 0, 243000, NULL, '2021-06-17 18:53:36', '2021-06-17 18:53:36', NULL),
            (18, '美業管家專業連鎖版（一年份）', 'g17', 12, 1, 17, 15000, 3000, 0, 258000, NULL, '2021-06-17 18:53:36', '2021-06-17 18:53:36', NULL),
            (19, '美業管家專業連鎖版（一年份）', 'g18', 12, 1, 18, 15000, 3000, 0, 273000, NULL, '2021-06-17 18:53:36', '2021-06-17 18:53:36', NULL),
            (20, '美業管家專業連鎖版（一年份）', 'g19', 12, 1, 19, 15000, 3000, 0, 288000, NULL, '2021-06-17 18:53:36', '2021-06-17 18:53:36', NULL),
            (30, '計算分店金額簡訊', NULL, 1, 0, 1, 1250, 84, 0, 0, NULL, '2021-06-17 15:56:03', '2021-06-17 15:56:03', NULL),
            (50, '簡訊 100 則', 's1', 0, NULL, NULL, NULL, 100, 0, 100, NULL, '2021-06-17 09:31:46', '2021-06-17 09:31:46', NULL),
            (51, '簡訊 300 則', 's2', 0, NULL, NULL, NULL, 300, 0, 300, NULL, '2021-06-17 09:31:48', '2021-06-17 09:31:48', NULL),
            (52, '簡訊 500 則', 's3', 0, NULL, NULL, NULL, 500, 0, 500, NULL, '2021-06-17 09:31:46', '2021-06-17 09:31:46', NULL),
            (53, '簡訊 1000 則', 's4', 0, NULL, NULL, NULL, 1000, 0, 1000, NULL, '2021-06-17 09:31:46', '2021-06-17 09:31:46', NULL),
            (54, '簡訊 2000 則', 's5', 0, NULL, NULL, NULL, 2000, 0, 2000, NULL, '2021-06-17 09:31:47', '2021-06-17 09:31:47', NULL),
            (200, '實力派管家專業版（二年份）', 'a2', 24, NULL, NULL, NULL, 2500, 0, 34000, NULL, '2021-06-17 15:30:43', '2021-06-17 15:30:43', '2021-06-17 15:30:32');";
            
        \DB::statement($sql) ;

        

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('buy_modes');
    }
}
