<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.5.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateShopManagementModesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('shop_management_modes', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('shop_id')->nullable()->comment('所屬商家');
            $table->string('type', 10)->nullable()->comment('once單次auto自動推廣');
            $table->string('name', 255)->nullable()->comment('活動描述');
            $table->date('start_date')->nullable()->comment('篩選起始時間/活動起始時間');
            $table->date('end_date')->nullable()->comment('篩選結束時間/活動結束時間');
            $table->string('keyword', 100)->nullable()->comment('姓名包含關鍵字');
            $table->char('consumption', 1)->nullable()->default('0')->comment('1有消費0無消費會員');
            $table->integer('min_price')->nullable()->comment('消費最小金額');
            $table->integer('max_price')->nullable()->comment('消費最大金額');
            $table->string('shop_staffs', 255)->nullable()->comment('服務人員(複選)');
            $table->text('shop_services')->nullable()->comment('服務項目(複選)');
            $table->string('sex', 10)->nullable()->comment('性別(複選)');
            $table->integer('min_age')->nullable()->comment('最小年齡');
            $table->integer('max_age')->nullable()->comment('最大年齡');
            $table->string('birthday_month', 30)->nullable()->comment('生日月份(複選)');
            $table->string('constellation', 50)->nullable()->comment('星座(複選)');
            $table->string('customer_level', 100)->nullable()->comment('顧客消費等級(複選)');
            $table->string('customer_tags', 255)->nullable()->comment('標籤');
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();

            $table->index('shop_id', 'shop_id');

            

        });

        

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('shop_management_modes');
    }
}
