<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.5.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateCompanyTopUpsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('company_top_ups', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('company_id')->nullable()->comment('所屬集團');
            $table->string('name', 30)->nullable()->comment('名稱');
            $table->integer('price')->nullable()->comment('顯示金額');
            $table->integer('during_type')->nullable()->comment('販售起迄選項1.無期限2.起迄時間');
            $table->date('start_date')->nullable()->comment('起始時間');
            $table->date('end_date')->nullable()->comment('結束時間');
            $table->integer('show_day')->nullable()->comment('販售幾天前自動上架顯示');
            $table->integer('use_coupon')->nullable()->comment('優惠券使否可以折抵0不可以,1可以');
            $table->integer('limit')->nullable()->comment('使用限制1無限制2全服務3全產品4部分');
            $table->enum('status', ['pending', 'published'])->nullable()->default('pending')->comment('狀態 pending:暫存 published:上架');
            $table->integer('view')->nullable()->comment('瀏覽次數');
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();

            $table->index('company_id', 'company_id');

            

        });

        

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('company_top_ups');
    }
}
