<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.5.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateCustomerLoyaltyCardsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('customer_loyalty_cards', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('customer_id')->nullable()->comment('主會員表id');
            $table->integer('company_id')->nullable()->comment('所屬集團');
            $table->integer('shop_id')->nullable()->comment('所屬商家');
            $table->integer('shop_loyalty_card_id')->nullable()->comment('商家集點卡');
            $table->string('card_no', 20)->nullable()->comment('卡號');
            $table->integer('full_point')->nullable()->comment('集滿要多少點數');
            $table->integer('last_point')->nullable()->comment('還需要多少點數集滿');
            $table->char('status', 1)->nullable()->default('N')->comment('使用狀態Y使用N未使用');
            $table->dateTime('using_time')->nullable()->comment('何時使用掉集點卡');
            $table->dateTime('created_at')->nullable()->default(\DB::raw('CURRENT_TIMESTAMP'));
            $table->dateTime('updated_at')->nullable()->default(\DB::raw('CURRENT_TIMESTAMP'));
            $table->integer('deleted_at')->nullable();

            $table->index('customer_id', 'customer_id');
            $table->index('shop_id', 'shop_id');
            $table->index('company_id', 'company_id');

            

        });

        

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('customer_loyalty_cards');
    }
}
