<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.5.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateMemberAddressesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('member_addresses', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('default')->nullable()->default(0)->comment('是否是預設地址');
            $table->string('companyId', 10)->nullable();
            $table->string('name', 10)->nullable()->comment('聯絡人姓名');
            $table->string('phone', 20)->nullable()->comment('聯絡電話');
            $table->string('city', 5)->nullable()->comment('縣市');
            $table->string('area', 10)->nullable()->comment('區');
            $table->string('address', 100)->nullable()->comment('地址');
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();

            $table->index('companyId', 'companyId');

            

        });

        

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('member_addresses');
    }
}
