<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.5.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateShopNoticesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('shop_notices', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('shop_id')->nullable()->comment('所屬商家');
            $table->string('type', 20)->nullable()->comment('before預約前/after服務後/give_back');
            $table->string('name', 255)->nullable()->comment('通知名稱');
            $table->text('content')->nullable()->comment('通知內容');
            $table->text('url')->nullable()->comment('連結');
            $table->text('shop_coupons')->nullable()->comment('優惠券(多張)');
            $table->integer('hour')->nullable()->comment('服務結束後多少小時');
            $table->integer('day')->nullable()->comment('服務的幾天前/後');
            $table->integer('send_type')->nullable()->comment('1手機與line 2手機 3line 4line優先');
            $table->text('shop_services')->nullable()->comment('商家服務(複選)');
            $table->enum('status', ['pending', 'published'])->nullable()->default('published')->comment('啟用/關閉');
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();

            

            

        });

        

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('shop_notices');
    }
}
