<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.5.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateShopCustomerReservationTagsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('shop_customer_reservation_tags', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('shop_id')->nullable()->comment('所屬商家');
            $table->integer('shop_customer_id')->nullable()->comment('所屬會員');
            $table->integer('shop_reservation_tag_id')->nullable()->comment('所屬預約標籤');
            $table->string('name', 50)->nullable()->comment('標籤名稱');
            $table->char('blacklist', 1)->nullable()->default('N')->comment('是否列入黑名稱Y是N否');
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();

            $table->index('shop_id', 'shop_id');
            $table->index('shop_customer_id', 'shop_customer_id');
            $table->index('shop_reservation_tag_id', 'shop_reservation_tag_id');

            

        });

        

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('shop_customer_reservation_tags');
    }
}
