<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.5.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateDirectSalesPointLogsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('direct_sales_point_logs', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('user_id')->nullable()->comment('使用者');
            $table->string('type', 10)->nullable()->comment('in/out');
            $table->integer('point')->nullable();
            $table->integer('extend_mode')->nullable()->comment('展延哪個方案');
            $table->integer('money')->nullable();
            $table->string('accounting', 255)->nullable();
            $table->integer('extend_month')->nullable()->comment('延展多久');
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();

            $table->index('user_id', 'user_id');

            

        });

        

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('direct_sales_point_logs');
    }
}
