<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.5.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateCustomerReservationsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('customer_reservations', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('customer_id')->nullable()->comment('顧客主表id');
            $table->integer('company_id')->nullable()->comment('所屬集團');
            $table->integer('shop_id')->nullable()->comment('所屬分店');
            $table->integer('shop_service_id')->nullable()->comment('所屬分店的服務');
            $table->integer('shop_staff_id')->nullable()->comment('所屬分店的員工');
            $table->dateTime('start')->nullable()->comment('預約起始時間');
            $table->dateTime('end')->nullable()->comment('預約結束時間');
            $table->integer('need_time')->nullable()->comment('此次預約所需時間');
            $table->string('google_calendar_id', 50)->nullable()->comment('google行事曆id');
            $table->char('status', 1)->nullable()->default('N')->comment('處理狀況Y商家確認N商家未確認');
            $table->char('cancel_status', 1)->nullable()->comment('C商家取消M客戶取消');
            $table->dateTime('check_time')->nullable()->comment('審核時間');
            $table->integer('check_user')->nullable()->comment('審核者');
            $table->char('tag', 1)->nullable()->comment('1到了 / 2爽約 / 3小遲到 / 4大遲到 / 5 提早');
            $table->integer('bill_id')->nullable()->comment('帳單');
            $table->integer('deposit_type')->nullable()->default(0)->comment('0不收訂金1自行處理2平台收取');
            $table->dateTime('deposit_time')->nullable()->comment('收款時間');
            $table->char('customer_reservation', 1)->nullable()->default('N')->comment('Y會員自行預約N商家預約');
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();
            $table->string('old_event_id', 20)->nullable();

            $table->index('shop_id', 'shop_id');
            $table->index('customer_id', 'customer_id');

            

        });

        

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('customer_reservations');
    }
}
