<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.5.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateCompanyStaffsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('company_staffs', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('user_id')->nullable()->comment('串連帳號');
            $table->integer('company_id')->comment('所屬公司');
            $table->string('staff_no', 10)->nullable()->comment('員工編號');
            $table->string('name', 50)->nullable()->comment('真實姓名');
            $table->string('nick_name', 20)->nullable()->comment('暱稱');
            $table->integer('company_title_id_a')->nullable()->comment('主要職稱');
            $table->integer('company_title_id_b')->nullable()->comment('次要職稱');
            $table->string('phone', 50)->nullable()->comment('手機號碼');
            $table->string('email', 50)->nullable()->comment('email');
            $table->date('onboard')->nullable()->comment('到職日');
            $table->string('line_id', 50)->nullable()->comment('line id');
            $table->string('photo', 255)->nullable()->comment('員工照片');
            $table->string('banner', 255)->nullable()->comment('員工背景圖');
            $table->text('info')->nullable()->comment('員工介紹');
            $table->integer('calendar_color_type')->nullable()->default(1)->comment('顏色選項1預設2自定');
            $table->string('calendar_color', 10)->nullable()->default('#AC8CD5')->comment('行事曆使用顏色');
            $table->string('calendar_token', 255)->nullable()->comment('google行事曆token');
            $table->integer('reservation_limit')->nullable()->default(1)->comment('預約身分限制1不限制2歸屬');
            $table->string('line_code', 255)->nullable()->comment('line code');
            $table->dateTime('created_at');
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('fire_time')->nullable()->comment('解聘時間');
            $table->dateTime('deleted_at')->nullable();

            $table->index('user_id', 'user_id');
            $table->index('company_id', 'company_id');

            

        });

        

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('company_staffs');
    }
}
