<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.5.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateShopSetsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('shop_sets', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('shop_id')->comment('所屬店家');
            $table->integer('color_select')->nullable()->comment('網頁主色選項1預設2自定');
            $table->string('color', 10)->nullable()->default('#9440a1')->comment('主題顏色');
            $table->integer('show_service_type')->nullable()->default(1)->comment('預約服務顯示樣式1圖文2條列');
            $table->integer('show_phone')->nullable()->default(1)->comment('預約電話顯示1顯示0不顯示');
            $table->string('line_photo', 100)->nullable()->comment('line@圖片');
            $table->integer('reservation_check')->nullable()->default(0)->comment('預約審核0不審核1需審核');
            $table->integer('reservation_during_type')->nullable()->default(1)->comment('1每月固定2只能約近3不限制');
            $table->integer('reservation_during_month_after')->nullable()->default(1)->comment('開放後幾個月時間可預約');
            $table->integer('reservation_during_month_close')->nullable()->comment('近幾個月開放預約');
            $table->integer('reservation_during_open')->nullable()->default(25)->comment('每個月固定幾號開放');
            $table->integer('reservation_limit_type')->nullable()->default(1)->comment('1.當日不可預約2距當日3不限制');
            $table->integer('reservation_limit_day')->nullable()->comment('距當日幾天以上');
            $table->integer('customer_edit_reservation')->nullable()->default(0)->comment('客戶幾天前可以修改預約的時間');
            $table->integer('reservation_repeat_time_type')->nullable()->default(0)->comment('0否1是');
            $table->integer('reservation_repeat_time')->nullable()->comment('可重複次數');
            $table->integer('reservation_overlapping_type')->nullable()->default(0)->comment('0否1是');
            $table->integer('reservation_overlapping_minute')->nullable()->comment('可重疊幾分鐘');
            $table->integer('buffer_time')->nullable()->comment('緩衝時間');
            $table->integer('deposit_type')->nullable()->default(0)->comment('0否1是');
            $table->integer('deposit_dollar')->nullable()->comment('訂金');
            $table->integer('deposit_handle')->nullable()->default(2)->comment('1自行處理2平台收取費用');
            $table->integer('tag_during')->nullable()->default(3)->comment('近幾個月重新計算');
            $table->integer('blacklist_limit')->nullable()->default(1)->comment('黑名單限制1不限制2不能預約3限制項目');
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();

            $table->index('shop_id', 'shop_id');

            

        });

        

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('shop_sets');
    }
}
