<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.5.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateCompanyLoyaltyCardLimitsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('company_loyalty_card_limits', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('company_id')->nullable()->comment('所屬集團');
            $table->integer('company_loyalty_card_id')->nullable()->comment('集點卡id');
            $table->string('type', 10)->nullable()->comment('service/product');
            $table->integer('commodity_id')->nullable()->comment('服務/產品的id');
            $table->dateTime('created_at')->nullable()->default(\DB::raw('CURRENT_TIMESTAMP'));
            $table->dateTime('updated_at')->nullable()->default(\DB::raw('CURRENT_TIMESTAMP'));

            

            

        });

        

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('company_loyalty_card_limits');
    }
}
