<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.5.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateCompanyTopUpLimitTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('company_top_up_limit', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('company_id')->nullable()->comment('所屬集團');
            $table->integer('company_top_up_id')->nullable()->comment('儲值金id');
            $table->integer('type')->nullable()->comment('product/service');
            $table->integer('commodity_id')->nullable()->comment('集團產品/服務id');
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();

            $table->index('company_top_up_id', 'company_to_up_id');

            

        });

        

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('company_top_up_limit');
    }
}
