<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.5.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateCompanyLoyaltyCardsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('company_loyalty_cards', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('company_id')->nullable()->comment('所屬集團');
            $table->string('name', 30)->nullable()->comment('規則說明');
            $table->integer('condition_type')->nullable()->comment('1消費金額2服務一次3消費一次');
            $table->integer('condition')->nullable()->comment('多少元一點');
            $table->integer('full_point')->nullable()->comment('集滿需要的點數');
            $table->integer('first_point')->nullable()->default(0)->comment('發卡起始點數');
            $table->integer('deadline_type')->nullable()->comment('有效期限1無期限2顧客獲得當日3最後一次集點4統一起迄');
            $table->integer('year')->nullable()->comment('有效期限幾年');
            $table->integer('month')->nullable()->comment('有效期限幾月');
            $table->date('start_date')->nullable()->comment('起始時間');
            $table->date('end_date')->nullable()->comment('結束時間');
            $table->text('content')->nullable()->comment('使用說明');
            $table->integer('background_type')->nullable()->comment('背景圖片樣式1選擇顏色2自定3上傳圖片');
            $table->string('background_color', 10)->nullable()->comment('背景顏色');
            $table->string('background_img', 255)->nullable()->comment('背景圖片');
            $table->integer('watermark_type')->nullable()->comment('1不使用圖片2上傳圖片');
            $table->string('watermark_img', 255)->nullable()->comment('點數浮水印圖片');
            $table->string('type', 20)->nullable()->comment('集點卡類型');
            $table->integer('second_type')->nullable()->comment('1:贈品從既有的2:贈品自定3體驗從既有的4:體驗自定5無門檻6滿額折抵');
            $table->string('commodityId', 20)->nullable()->comment('既有的產品/服務的id');
            $table->string('self_definition', 50)->nullable()->comment('自定名稱');
            $table->integer('price')->nullable()->comment('價格/折抵金額');
            $table->integer('consumption')->nullable()->comment('消費金額');
            $table->integer('limit')->nullable()->comment('使用限制1無限制2全服務3全產品4部分');
            $table->integer('get_limit')->nullable()->comment('1無限制2同一天不重複3有時間限制不重複');
            $table->integer('get_limit_minute')->nullable()->comment('幾分鐘內不重複領取');
            $table->integer('discount_limit_type')->nullable()->comment('1無期限2一個月3三個月4六個月5一年6自定');
            $table->integer('discount_limit_month')->nullable()->comment('期限使用幾個月內');
            $table->integer('notice_day')->nullable()->comment('失效前幾天提醒');
            $table->enum('status', ['pending', 'published'])->nullable()->default('pending')->comment('狀態 pending:暫存 published:上架');
            $table->integer('view')->nullable()->default(0)->comment('觀看次數');
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();

            $table->index('company_id', 'company_id');

            

        });

        

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('company_loyalty_cards');
    }
}
