<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.5.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateMessageLogsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('message_logs', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('company_id')->nullable()->comment('所屬集團');
            $table->integer('shop_id')->nullable()->comment('所屬商家');
            $table->string('phone', 20)->nullable()->comment('電話號碼');
            $table->text('content')->nullable()->comment('發送內容');
            $table->integer('use')->nullable()->comment('此次發送簡訊數量');
            $table->date('reservation')->nullable()->comment('預約發送日期');
            $table->integer('customer_reservation_id')->nullable()->comment('顧客預約');
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();

            

            

        });

        

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('message_logs');
    }
}
