<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.5.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateLineControllsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('line_controlls', function (Blueprint $table) {
            $table->integer('id');
            $table->string('line_code', 100)->nullable();
            $table->string('pin', 10)->nullable()->comment('手機驗證碼');
            $table->string('line_name', 255)->nullable()->comment('line綁訂姓名');
            $table->string('phone', 10)->nullable();
            $table->integer('status')->nullable()->default(0)->comment('0尚未綁訂,1有輸入電話,2有輸入驗證碼,3尚未開通管理台,4綁訂完成,5修改電話號碼');
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();

            $table->primary('id');

            

        });

        

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('line_controlls');
    }
}
