<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.5.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateCompanyCouponsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('company_coupons', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('company_id')->nullable()->comment('所屬集團');
            $table->string('type', 20)->nullable()->comment('優惠券類型');
            $table->string('title', 60)->nullable()->comment('大標題');
            $table->string('description', 60)->nullable()->comment('小標題');
            $table->date('start_date')->nullable()->comment('開始時間');
            $table->date('end_date')->nullable()->comment('結束時間');
            $table->integer('consumption')->nullable()->comment('消費金額');
            $table->double('discount', 8, 2)->nullable()->comment('折扣折數');
            $table->integer('price')->nullable()->comment('價格/折抵金額');
            $table->integer('count_type')->nullable()->comment('1不限2自定數量');
            $table->integer('count')->nullable()->comment('可使用數量');
            $table->integer('second_type')->nullable()->comment('1:從既有的2:自定3無門檻4滿額折抵');
            $table->string('commodityId', 20)->nullable()->comment('既有的產品/服務的id，根據type到指定資料表拿取');
            $table->string('self_definition', 50)->nullable()->comment('自己定義名稱');
            $table->integer('photo_type')->nullable()->comment('1:不使用2預設3上傳圖片');
            $table->string('photo', 255)->nullable()->comment('圖片');
            $table->integer('use_type')->nullable()->comment('1只能領一次2不限次數');
            $table->integer('get_level')->nullable()->default(1)->comment('領取身分1.所有人2消費等級3特殊身分4簡訊會員');
            $table->integer('customer_level')->nullable()->comment('等級');
            $table->integer('show_type')->nullable()->comment('1該身分才看得到2所有人');
            $table->string('limit', 10)->nullable()->comment('使用限制1無限制2全服務3全產品4部分');
            $table->text('content')->nullable()->comment('使用說明');
            $table->enum('status', ['pending', 'published'])->nullable()->default('pending')->comment('狀態 pending:暫存 published:上架');
            $table->integer('view')->nullable()->default(0)->comment('觀看次數');
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();

            $table->index('company_id', 'companyId');

            

        });

        

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('company_coupons');
    }
}
